---
title: "Take-Home_midterm"
author: "Elliot Metviner"
date: "10/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
```


```{r}
pop.data <- read.csv("https://www2.census.gov/programs-surveys/popest/datasets/2010-2019/counties/asrh/cc-est2019-agesex-39.csv")


```

```{r}
pop.data1 <- pop.data %>%
  filter(YEAR == "3") %>%
  mutate("POPESTIMATEYR3"= POPESTIMATE) %>%
  select("CTYNAME", "POPESTIMATEYR3")

pop.data2 <- pop.data %>%
  filter(YEAR == "12") %>% 
  mutate("POPESTIMATEYR12" = POPESTIMATE) %>%
  select("CTYNAME", "POPESTIMATEYR12")

pop.change <- merge(pop.data1, pop.data2, by.x="CTYNAME", by.y="CTYNAME")



## Created two data frames for both years, then merged the two datas together, and grouped by county name to make future code easier, re named pop estimate to the relative population estimate for the year to also help with future code. 
```


**Total Population % change between years 3 and 12**

```{r}
pop.change1 <- pop.change %>%
  mutate("Pop.Change" = POPESTIMATEYR12 - POPESTIMATEYR3) %>%
  mutate("Perc.Change" = Pop.Change/POPESTIMATEYR3*100) %>%
  select("CTYNAME", "Perc.Change")

view(pop.change1) 

pop.change1 %>%
  arrange(desc(Perc.Change)) %>%
  slice(1:3)

pop.change1 %>%
  arrange(desc(Perc.Change)) %>%
  slice(86:88)

## Calculated % population change, and mutated the data set so it only included only percent change for the individual counties.
```



**Percent population change for people 65+**
```{r}
OA.data <- pop.data %>%
  filter(YEAR == "3") %>%
  mutate("POPESTIMATEYR3"= AGE65PLUS_TOT) %>%
  select("CTYNAME", "POPESTIMATEYR3")

OA.data2 <- pop.data %>%
  filter(YEAR == "12") %>% 
  mutate("POPESTIMATEYR12" = AGE65PLUS_TOT) %>%
  select("CTYNAME", "POPESTIMATEYR12")

OA.change <- merge(OA.data, OA.data2, by.x="CTYNAME", by.y="CTYNAME")

OA.change <- OA.change %>%
  mutate("Pop.Change" = POPESTIMATEYR12 - POPESTIMATEYR3) %>%
  mutate("Perc.Change" = Pop.Change/POPESTIMATEYR3*100) %>%
  select("CTYNAME", "Perc.Change")



OA.change %>%
  arrange(desc(Perc.Change)) %>%
  slice(1:3)

OA.change %>%
  arrange(desc(Perc.Change)) %>%
  slice(86:88)

```




```{r}
YA.data1 <- pop.data %>%
  filter(YEAR == "3") %>%
  mutate("POPESTIMATEYR3"= UNDER5_TOT + AGE59_TOT + AGE1014_TOT + AGE1519_TOT) %>%
  select("CTYNAME", "POPESTIMATEYR3")

YA.data2 <- pop.data %>%
  filter(YEAR == "12") %>% 
  mutate("POPESTIMATEYR12" = UNDER5_TOT + AGE59_TOT + AGE1014_TOT + AGE1519_TOT) %>%
  select("CTYNAME", "POPESTIMATEYR12")

YA.change <- merge(YA.data1, YA.data2, by.x="CTYNAME", by.y="CTYNAME")


YA.change <- YA.change %>%
  mutate("Pop.Change" = POPESTIMATEYR12 - POPESTIMATEYR3) %>%
  mutate("Perc.Change" = Pop.Change/POPESTIMATEYR3*100) %>%
  select("CTYNAME", "Perc.Change")


YA.change %>%
  arrange(desc(Perc.Change)) %>%
  slice(1:3)

YA.change %>%
  arrange(desc(Perc.Change)) %>%
  slice(86:88)

```


